author           = InnovAnon
depends          = default,3d_armor,edit_skin,ia_gender,ia_names,ia_util,name_generator,persistencelib,player_monoids
description      = Humanoid Mobs Lib
name             = ia_humanoid
optional_depends =
title            = IA Humanoid Mobs Lib

